name: AdminTools
main: to.joe.j2mc.admintoolkit.J2MC_AdminToolkit
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Admin toolkit module.
commands:
  gm:
    description: gamemode
    usage: /gm
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  getgroup:
    description: fetches the user's group
    usage: /getgroup player
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  hat:
    description: adds item in hand to helmet slot
    usage: /hat
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  whereis:
     description: gets the coordinates of a player
     usage: /whereis player
     permission: j2mc.admintoolkit.admin
     permission-message: Not an admin
  a:
    description: chat privately \o/
    usage: /a message
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  g:
    description: Big brother wishes to talk to you
    usage: /g message
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  time:
    description: change time
    usage: /time <day/night>
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  mob:
    description: spawns mob
    usage: /mob name
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  coo:
    description: teleport to coords
    usage: /coo x y z
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  getflags:
    description: get a player's flags
    usage: /getflags player
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  storm:
    description: start and stop storms
    usage: /storm start/stop
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  whois:
    description: get info on a user
    usage: /whois player
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  kibbles:
    description: wax on
    usage: /kibbles
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
  bits:
    description: wax off
    usage: /bits
    permission: j2mc.admintoolkit.admin
    permission-message: Not an admin
permissions:
  j2mc.admintoolkit.admin:
    description: Admin

